In [14]:
import numpy as np 
import pandas as pd 

from datetime import datetime
from dateutil.relativedelta import relativedelta

In [2]:
df = pd.read_csv('anime.csv')

In [3]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [4]:
df.loc[0]['Title']

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [5]:
def extract_eps(txt):
    ep = ""
    check = False
    for i in txt:
        if i == ")":
            break
        if check == True:
            ep += i
        if i == "(": 
            check = True
     
    return ep

##### make a new column for episode count

In [6]:
df['Episodes'] = df['Title'].apply(extract_eps)

In [7]:
df['Episodes'] = df['Episodes'].str.replace(" eps", "")

In [8]:
df['Episodes'] = df['Episodes'].astype(int)

##### make a new column for time stamp

In [9]:
df.iloc[0]['Title']

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [10]:
def extract_time(txt): 
    time_stamp = ''
    for i in range(len(txt)): 
        if txt[i] == ')':
            for j in range(i+1,i+20):
                time_stamp += txt[j]
    return time_stamp

In [11]:
df['Total_Time'] = df['Title'].apply(extract_time)
df.head()

,Rank,Title,Score,Episodes,Total_Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [15]:
def extract_months(txt):
    start_txt, end_txt = txt.split(" - ")

    start = datetime.strptime(start_txt, "%b %Y")
    end = datetime.strptime(end_txt, "%b %Y")

    diff = relativedelta(end, start)

    total_months = diff.years * 12 + diff.months

    return total_months


df["Total_Months"] = df["Total_Time"].apply(extract_months)

In [16]:
df.head()

,Rank,Title,Score,Episodes,Total_Time,Total_Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,3

##### which anime has the highest score

In [17]:
df[df['Score'] == df['Score'].max()]

,Rank,Title,Score,Episodes,Total_Time,Total_Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010,15

##### give me top 5 highest scoring anime

In [18]:
df.head() #The Table Is Already Sorted

,Rank,Title,Score,Episodes,Total_Time,Total_Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,3

##### which anime has the highest episode count

In [19]:
df[df['Episodes'] == df['Episodes'].max()]

,Rank,Title,Score,Episodes,Total_Time,Total_Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,47

##### animes with top 5 episode count

In [22]:
df.sort_values(by= 'Episodes', ascending= False).head()

,Rank,Title,Score,Episodes,Total_Time,Total_Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,47
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,35
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,110
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,17
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,17

##### which is the longest running anime

In [20]:
df[df['Total_Months'] == df['Total_Months'].max()]

,Rank,Title,Score,Episodes,Total_Time,Total_Months
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,110